Repository proLmpa/NBC_2tWasSummer, pull requests merged in 2023-08, with the labels that each got.

#5 [docs] readme 틀 만들기
  README.md
Labels: documentation

#7 [docs] PR Template 팀 이름 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#22 [init] Comment 기본 파일 생성 및 기능 구현
  src/main/java/com/example/itwassummer/card/entity/Card.java
  src/main/java/com/example/itwassummer/comment/controller/CommentController.java
  src/main/java/com/example/itwassummer/comment/dto/CommentCreateRequestDto.java
  src/main/java/com/example/itwassummer/comment/dto/CommentEditRequestDto.java
  src/main/java/com/example/itwassummer/comment/dto/CommentResponseDto.java
  src/main/java/com/example/itwassummer/comment/entity/Comment.java
  src/main/java/com/example/itwassummer/comment/repository/CommentRepository.java
  src/main/java/com/example/itwassummer/comment/service/CommentService.java
  src/main/java/com/example/itwassummer/comment/service/CommentServiceImpl.java
Labels: enhancement

#26 [docs] Github Action 코드 구현(테스트 코드 처리 X)
  .github/workflows/dev-CI.yml
Labels: documentation

#31 [hotfix] build Test 안되는 오류 수정
  .github/workflows/dev-CI.yml
Labels: fix

#25 [init] Label 도메인 기본 파일 생성 (
  src/main/java/com/example/itwassummer/label/controller/LabelController.java
  src/main/java/com/example/itwassummer/label/dto/LabelCreateRequestDto.java
  src/main/java/com/example/itwassummer/label/dto/LabelEditRequestDto.java
  src/main/java/com/example/itwassummer/label/dto/LabelResponseDto.java
  src/main/java/com/example/itwassummer/label/entity/Label.java
  src/main/java/com/example/itwassummer/label/repository/LabelRepository.java
  src/main/java/com/example/itwassummer/label/service/LabelService.java
  src/main/java/com/example/itwassummer/label/service/LabelServiceImpl.java
Labels: enhancement

#33 [Feature] 카드 CRUD 초기 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/example/itwassummer/card/controller/CardController.java
  src/main/java/com/example/itwassummer/card/dto/CardRequestDto.java
  src/main/java/com/example/itwassummer/card/dto/CardResponseDto.java
  src/main/java/com/example/itwassummer/card/entity/Card.java
  src/main/java/com/example/itwassummer/card/repository/CardRepository.java
  src/main/java/com/example/itwassummer/card/repository/CardRepositoryImpl.java
  src/main/java/com/example/itwassummer/card/repository/CustomCardRepository.java
  src/main/java/com/example/itwassummer/card/service/CardService.java
  src/main/java/com/example/itwassummer/card/service/CardServiceImpl.java
  src/main/java/com/example/itwassummer/cardmember/dto/CardMemberResponseDto.java
  src/main/java/com/example/itwassummer/cardmember/entity/CardMember.java
  src/main/java/com/example/itwassummer/cardmember/repository/CardMemberRepository.java
  src/main/java/com/example/itwassummer/cardnotification/dto/CardNotificationResponseDto.java
  src/main/java/com/example/itwassummer/cardnotification/entity/CardNotification.java
  src/main/java/com/example/itwassummer/common/config/AmazonS3Config.java
  src/main/java/com/example/itwassummer/common/config/QueryDslConfig.java
  src/main/java/com/example/itwassummer/common/error/CustomErrorCode.java
  src/main/java/com/example/itwassummer/common/exception/GlobalControllerAdvice.java
  src/main/java/com/example/itwassummer/common/file/FileUploader.java
  src/main/java/com/example/itwassummer/common/file/S3FileDto.java
  src/main/resources/application.properties
  src/test/java/com/example/itwassummer/card/controller/CardControllerTest.java
  src/test/java/com/example/itwassummer/card/repository/CardRepositoryTest.java
Labels: enhancement, develop

#29 [init] Board 기본 파일 생성 (Board 참여자 작업하지 않음)
  build.gradle
  settings.gradle
  src/main/java/com/example/itwassummer/board/controller/BoardController.java
  src/main/java/com/example/itwassummer/board/dto/BoardRequestDto.java
  src/main/java/com/example/itwassummer/board/dto/BoardResponseDto.java
  src/main/java/com/example/itwassummer/board/entity/Board.java
  src/main/java/com/example/itwassummer/board/entity/BoardMembers.java
  src/main/java/com/example/itwassummer/board/repository/BoardRepository.java
  src/main/java/com/example/itwassummer/board/service/BoardService.java
  src/main/java/com/example/itwassummer/board/service/BoardServiceImpl.java
  src/main/java/com/example/itwassummer/card/controller/CardController.java
  src/main/java/com/example/itwassummer/common/error/CustomErrorCode.java
  src/main/java/com/example/itwassummer/deck/entity/Deck.java
  src/main/java/com/example/itwassummer/user/entity/User.java
  src/main/resources/application.properties
Labels: question

#35 [init] CardLabel 기본 파일 생성
  src/main/java/com/example/itwassummer/card/entity/Card.java
  src/main/java/com/example/itwassummer/cardlabel/controller/CardLabelController.java
  src/main/java/com/example/itwassummer/cardlabel/entity/CardLabel.java
  src/main/java/com/example/itwassummer/cardlabel/repository/CardLabelRepository.java
  src/main/java/com/example/itwassummer/cardlabel/service/CardLabelService.java
  src/main/java/com/example/itwassummer/cardlabel/service/CardLabelServiceImpl.java
  src/main/java/com/example/itwassummer/comment/service/CommentServiceImpl.java
  src/main/java/com/example/itwassummer/common/error/CustomErrorCode.java
  src/main/java/com/example/itwassummer/common/exception/CustomException.java
  src/main/java/com/example/itwassummer/label/service/LabelServiceImpl.java
Labels: enhancement

#46 [feature] Board - Label 연관 관계 매핑 후 관련 기능 구현
  src/main/java/com/example/itwassummer/board/entity/Board.java
  src/main/java/com/example/itwassummer/board/service/BoardServiceImpl.java
  src/main/java/com/example/itwassummer/common/config/WebSecurityConfig.java
  src/main/java/com/example/itwassummer/common/error/CustomErrorCode.java
  src/main/java/com/example/itwassummer/label/controller/LabelController.java
  src/main/java/com/example/itwassummer/label/dto/LabelEditRequestDto.java
  src/main/java/com/example/itwassummer/label/dto/LabelRequestDto.java
  src/main/java/com/example/itwassummer/label/dto/LabelResponseDto.java
  src/main/java/com/example/itwassummer/label/entity/Label.java
  src/main/java/com/example/itwassummer/label/repository/LabelRepository.java
  src/main/java/com/example/itwassummer/label/service/LabelService.java
  src/main/java/com/example/itwassummer/label/service/LabelServiceImpl.java
  src/main/java/com/example/itwassummer/user/service/UserServiceImpl.java
Labels: enhancement, develop

#32 [feature] Deck CRUD 구현 완료
  src/main/java/com/example/itwassummer/common/error/CustomErrorCode.java
  src/main/java/com/example/itwassummer/deck/controller/DeckController.java
  src/main/java/com/example/itwassummer/deck/dto/DeckMoveRequestDto.java
  src/main/java/com/example/itwassummer/deck/dto/DeckResponseDto.java
  src/main/java/com/example/itwassummer/deck/entity/Deck.java
  src/main/java/com/example/itwassummer/deck/repository/DeckCustomRepository.java
  src/main/java/com/example/itwassummer/deck/repository/DeckRepository.java
  src/main/java/com/example/itwassummer/deck/repository/DeckRepositoryImpl.java
  src/main/java/com/example/itwassummer/deck/service/DeckService.java
  src/main/java/com/example/itwassummer/deck/service/DeckServiceImpl.java
Labels: enhancement

#55 [feature] Deck 복구 관련 기능 구현 완!
  src/main/java/com/example/itwassummer/common/error/CustomErrorCode.java
  src/main/java/com/example/itwassummer/deck/controller/DeckController.java
  src/main/java/com/example/itwassummer/deck/dto/DeckResponseDto.java
  src/main/java/com/example/itwassummer/deck/entity/Deck.java
  src/main/java/com/example/itwassummer/deck/repository/DeckRepository.java
  src/main/java/com/example/itwassummer/deck/service/DeckService.java
  src/main/java/com/example/itwassummer/deck/service/DeckServiceImpl.java
Labels: enhancement

#56 [docs] Action에 DB 연결 코드 추가(스프링 부트 테스트 가능!!) - 테스트 완!
  .github/workflows/dev-CI.yml
Labels: CI

#58 [refactor] Deck 테스트 작성 완료 - CI 통과!!!!!
  src/main/java/com/example/itwassummer/deck/repository/DeckRepository.java
  src/main/java/com/example/itwassummer/deck/service/DeckServiceImpl.java
  src/test/java/com/example/itwassummer/deck/service/DeckServiceTest.java
Labels: refactor
